### ISSUE TITLE
Temperature Attribute

### ISSUE THREAD

**Issue by Sebbo02** [mfkrause/homebridge-sunposition#2]
Hi,

would it be possible to also add the attribute temperature as an optional value? This would be the perfect solution for sun shades which do not need to be closed on cooler days. Thanks a lot!

**Comment by mfkrause** [comment]
Hey, thanks for the input -- unfortunately, this isn't within the purpose of the plug-in and would require a connection to a third-party weather API such as Dark Sky. I would recommend looking for another Homebridge plugin which exposes the temperature to HomeKit, so that you can create an automation with the input from this plugin here & the weather plugin directly within HomeKit.
